version: '3.8'
services:
  # Django app
  backend_cryptography:
    container_name: boomslag_ms_cryptography
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8019"
    volumes:
      - .:/app
    ports:
      - 8019:8019
    depends_on:
      - db_cryptography
      - redis
  # Event Queue Kafka
  queue_cryptography:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db_cryptography
  
  # Database (PostgreSQL)
  db_cryptography:
    image: postgres
    container_name: django_cryptography_api_postgresql
    restart: always
    environment:
      POSTGRES_DB: boomslag_cryptography_db
      POSTGRES_USER: boomslag
      POSTGRES_PASSWORD: postgres
    ports:
      - 5451:5432
    volumes:
      - .dbdata:/var/lib/postgresql
  # Redis Cache
  redis:
    image: redis
    container_name: django_cryptography_api_redis
    ports:
      - 6348:6379